[package]
name = "ts-parsers"
version = "0.0.0"
edition = "2021"
authors = ["Kevin Silveter"]
description = "A tool to manage tree-sitter parsers used by nvim-treesitter"
repository = "https://github.com/KevinSilveter/ts-parsers"
homepage = "https://github.com/KevinSilveter/ts-parsers"

[dependencies]
ahash = { version = "0.8.9", features = ["serde"] }
ansi_term = "0.12.1"
anyhow = "1.0.79"
async-trait = "0.1.77"
bzip2 = "0.4.4"
cfg-if = "1.0.0"
chrono = { version = "0.4.33", features = ["clock", "serde"] }
clap = { version = "4.4.18", features = ["derive", "color"] }
crossterm = "0.27.0"
dirs = "5.0.1"
flate2 = "1.0.28"
fs_extra = "1.3.0"
lazy_static = "1.4.0"
reqwest = { version = "0.11.24", default-features = false, features = [
   "json",
   "rustls-tls",
] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
shellexpand = "3.1.0"
strip-ansi-escapes = "0.2.0"
tar = "0.4.40"
tempfile = "3.10.0"
tokio = { version = "1.36.0", features = [
   "macros",
   "signal",
   "sync",
] }
tokio-process-stream = "0.4.0"
tokio-stream = "0.1.14"

[dev-dependencies]
assert_cmd = { version = "2.0.14", features = ["color"] }
jsonschema = "0.17.1"
predicates = "3.1.0"
rusty-hook = "0.11.2"

[profile.release]
strip = true
codegen-units = 1
opt-level = 3
lto = "thin"
