name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig (macos)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          wget 'https://ziglang.org/download/0.13.0/zig-macos-x86_64-0.13.0.tar.xz' -O /tmp/zig.tar.xz
          tar -xf /tmp/zig.tar.xz -C /tmp
          mkdir -p $HOME/zig
          mv /tmp/zig-macos-x86_64-0.13.0/* $HOME/zig
          echo "$HOME/zig" >> $GITHUB_PATH

      - name: Install Zig (linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          wget 'https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz' -O /tmp/zig.tar.xz
          tar -xf /tmp/zig.tar.xz -C /tmp
          mkdir -p $HOME/zig
          mv /tmp/zig-linux-x86_64-0.13.0/* $HOME/zig
          echo "$HOME/zig" >> $GITHUB_PATH

      - name: Install Zig (windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri 'https://ziglang.org/download/0.13.0/zig-windows-x86_64-0.13.0.zip' -OutFile "$env:TEMP\zig.zip"
          7z x "$env:TEMP\zig.zip" -o"$env:TEMP"
          New-Item -Type Directory -Path $env:USERPROFILE\zig
          Move-Item -Path "$env:TEMP\zig-windows-x86_64-0.13.0\*" -Destination "$env:USERPROFILE\zig"
          "$env:USERPROFILE\zig" >> $env:GITHUB_PATH

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          cache-key: ${{ runner.os }}-cargo-nextest

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tree-sitter-cli
          cache-key: ${{ runner.os }}-tree-sitter-cli

      - name: Run Tests
        shell: bash
        run: cargo nextest --no-fail-fast
