name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig (macos)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          wget 'https://ziglang.org/download/0.11.0/zig-macos-x86_64-0.11.0.tar.xz' -O /tmp/zig.tar.xz
          tar -xf /tmp/zig.tar.xz -C /tmp
          mkdir -p $HOME/zig
          cp -r /tmp/zig-macos-x86_64-0.11.0/* $HOME/zig
          echo "$HOME/zig" >> $GITHUB_PATH

      - name: Setup Zig (linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          wget 'https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz' -O /tmp/zig.tar.xz
          tar -xf /tmp/zig.tar.xz -C /tmp
          mkdir -p $HOME/zig
          cp -r /tmp/zig-linux-x86_64-0.11.0/* $HOME/zig
          echo "$HOME/zig" >> $GITHUB_PATH

      - name: Setup Zig (windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri 'https://ziglang.org/download/0.11.0/zig-windows-x86_64-0.11.0.zip' -OutFile "$env:TEMP\zig.zip"
          7z x "$env:TEMP\zig.zip" -o"$env:TEMP"
          New-Item -Type Directory -Path $env:USERPROFILE\zig
          Move-Item -Path "$env:TEMP\zig-windows-x86_64-0.11.0\*" -Destination "$env:USERPROFILE\zig"
          "$env:USERPROFILE\zig" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "$env:USERPROFILE\zig"
          "$env:Path"
          "$evn:GITHUB_PATH"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8

      - name: Install tree-sitter-cli
        shell: bash
        run: cargo install tree-sitter-cli

      - name: Run Tests
        shell: bash
        run: cargo test
